CREATE DATABASE IF NOT EXISTS practice CHARSET='UTF8'
SHOW CREATE DATABASE IF NOT EXISTS practice;
SHOW DATABASES;
USE PRACTICE;
SELECT DATABASE();
ALTER DATABASE PRACTICE CHARSET='GBK';
ALTER DATABASE PRACTICE CHARSET='UTF8';

CREATE TABLE student(
    id INT,
    name VARCHAR(10)
);
SHOW TABLES;
SHOW CREATE TABLE student;
DESC stu;
RENAME TABLE student TO STU;
ALTER TABLE STU ADD AGE INT NOT NULL;
ALTER TABLE STU DROP AGE;
ALTER TABLE STU CHANGE AGE ADDR VARCHAR(20) PRIMARY KEY;
ALTER TABLE STU MODIFY ADDR INT;




